package hello;

import hello.model.EnergyReading;
import hello.model.EnergyReadingRepository;
import hello.model.WindTurbine;
import hello.model.WindTurbineRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.sql.Timestamp;
import java.util.List;

/*
 *  POST    http://localhost:8080/demo/add      body: name=CK400, latitude=43.87, longitude=28.38
 *  GET     http://localhost:8080/demo/all
 *  POST    http://localhost:8080/demo/data     body: windTurbineName=CK400, time=2019-01-01%2015:30:00.0, value=300
 *  GET     http://localhost:8080/demo/data
 */


@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class ApiController {

    @Autowired // This means to get the bean called windTurbineRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private WindTurbineRepository windTurbineRepository;

    @Autowired
    private EnergyReadingRepository energyReadingRepository;

    public ApiController() {
    }

    @PostMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewWindTurbine (@RequestParam Float latitude
            , @RequestParam Float longitude, @RequestParam String name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        WindTurbine n = new WindTurbine(latitude, longitude, name);
        windTurbineRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<WindTurbine> getAllWindTurbines() {
        // This returns a JSON or XML with the wind turbines
        return windTurbineRepository.findAll();
    }

    @PostMapping(path="/data") // Map ONLY GET Requests
    public @ResponseBody String addNewEnergyReading (@RequestParam String windTurbineName
            , @RequestParam Float value, @RequestParam Timestamp time) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        List<WindTurbine> windTurbineList = windTurbineRepository.findByName(windTurbineName);
        if (windTurbineList.isEmpty())
            return "WindTurbine with name "+windTurbineName+" could not be found";
        WindTurbine windTurbine = windTurbineList.get(0);

        EnergyReading newEnergyReading = new EnergyReading(windTurbine, time, value);
        // "manually" deciding whether to save or update
        // but also take a look at the saveOrUpdate in hibernate and unsaved-value checks
        List<EnergyReading> energyReadings = energyReadingRepository.findByWindTurbineAndTime(windTurbine, time);
        if (energyReadings.isEmpty()) {
            energyReadingRepository.save(newEnergyReading);
        } else {
            energyReadings.get(0).setValue(value);
            energyReadingRepository.save(energyReadings.get(0));
        }
        
        return "Saved";
    }

    @GetMapping(path="/data")
    public @ResponseBody Iterable<EnergyReading> getAllData() {
        // This returns a JSON or XML with the energy readings
        return energyReadingRepository.findAll();
    }
}