package hello;

import hello.model.WindTurbineRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class VizController {

    @Autowired // This means to get the bean called windTurbineRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private WindTurbineRepository windTurbineRepository;

    @GetMapping("/map")
    public String map(Model model) {
        model.addAttribute("windTurbines", windTurbineRepository.findAll());
        return "map";
    }

}